use crate::{auth, error::{ApiError,ApiResult}, util, AppState};
use axum::{extract::{Query,State}, http::{HeaderMap,StatusCode}, Json};
use base64::{engine::general_purpose::{STANDARD_NO_PAD,URL_SAFE_NO_PAD},Engine as _};
use chrono::Duration;
use rusqlite::OptionalExtension;
use serde::Deserialize;
use serde_json::{json,Value};
use std::collections::HashSet;

const VERSION:i64=4;

#[derive(Deserialize)] struct Otk { key_id:String, public_key:String, signature:String }
#[derive(Deserialize)] pub struct Bundle { version:i64,bundle_version:i64,curve25519_identity_key:String,ed25519_identity_key:String,signed_payload:String,signature:String,#[serde(default)]one_time_keys:Vec<Otk> }
#[derive(Deserialize)] pub struct Claim {version:i64,target_device_id:String}
#[derive(Deserialize)] struct Envelope {message_id:String,recipient_device_id:String,sender_curve25519_key:String,session_id:String,message_type:i64,ciphertext:String,ciphertext_sha256:String}
#[derive(Deserialize)] pub struct EnvelopeBatch {version:i64,envelopes:Vec<Envelope>}
#[derive(Deserialize,Default)] pub struct EnvelopeQuery {after_sequence:Option<i64>,limit:Option<i64>}
#[derive(Deserialize)] pub struct Reserve {version:i64,chat_id:String,rotation_id:String}
#[derive(Deserialize)] struct GroupPackage {recipient_device_id:String,olm_session_id:String,message_type:i64,encrypted_session_key:String}
#[derive(Deserialize)] pub struct GroupSession {version:i64,chat_id:String,room_key_version:i64,session_id:String,rotation_id:String,packages:Vec<GroupPackage>}
#[derive(Deserialize,Default)] pub struct PackageQuery {limit:Option<i64>}
#[derive(Deserialize)] pub struct Consume {version:i64,chat_id:String,room_key_version:i64}

fn valid_curve(v:&str)->bool {
    if v.len()<32||v.len()>128||v.bytes().any(|b|b.is_ascii_whitespace()) {return false;}
    STANDARD_NO_PAD.decode(v).map(|b|(32..=64).contains(&b.len())).unwrap_or(false)
}
fn decode_url(v:&str,min:usize,max:usize)->ApiResult<Vec<u8>> { let b=URL_SAFE_NO_PAD.decode(v).map_err(|_|ApiError::bad("invalid_request"))?; if b.len()<min||b.len()>max{return Err(ApiError::bad("invalid_request"));} Ok(b) }
async fn member(state:&AppState,user:String,chat:String)->ApiResult<()> {let ok=state.db.run(move|c|Ok(c.query_row("SELECT EXISTS(SELECT 1 FROM chat_members WHERE chat_id=?1 AND username=?2)",rusqlite::params![chat,user],|r|r.get::<_,i64>(0))?==1)).await.map_err(ApiError::Internal)?;if !ok{return Err(ApiError::forbidden("forbidden"));}Ok(())}
async fn device_sig(state:&AppState,device:String,payload:Vec<u8>,sig:Vec<u8>)->ApiResult<bool>{state.db.run(move|c|{let row=c.query_row("SELECT key_algorithm,public_key_spki FROM provisioning_devices WHERE id=?1 AND revoked_at IS NULL",[device],|r|Ok((r.get::<_,String>(0)?,r.get::<_,Vec<u8>>(1)?))).optional()?;Ok(row.map(|(a,k)|auth::verify_signature(&a,&k,&payload,&sig)).unwrap_or(false))}).await.map_err(ApiError::Internal)}

pub async fn put_bundle(State(state):State<AppState>,headers:HeaderMap,Json(req):Json<Bundle>)->ApiResult<Json<Value>> {
    let p=auth::authenticate(&state,&headers,true).await?;
    if req.version!=VERSION || !(1..=64).contains(&req.bundle_version) || !valid_curve(&req.curve25519_identity_key)||!valid_curve(&req.ed25519_identity_key)||req.one_time_keys.len()>100{return Err(ApiError::bad("invalid_request"));}
    let payload=decode_url(&req.signed_payload,32,65536)?;let signature=decode_url(&req.signature,32,2048)?;
    let canonical=format!("fedmes-ratchet-bundle-v1\n{}\n{}\n{}\n{}",p.device_id,req.bundle_version,req.curve25519_identity_key,req.ed25519_identity_key).into_bytes();
    if payload!=canonical || !device_sig(&state,p.device_id.clone(),canonical,signature.clone()).await?{return Err(ApiError::forbidden("signature_invalid"));}
    let mut seen=HashSet::new(); let mut decoded=Vec::new();
    for x in req.one_time_keys { if x.key_id.is_empty()||x.key_id.len()>128||!valid_curve(&x.public_key)||!seen.insert(x.key_id.clone()){return Err(ApiError::bad("invalid_request"));} let sig=decode_url(&x.signature,32,2048)?;let msg=format!("fedmes-olm-otk-v1\n{}\n{}\n{}",p.device_id,x.key_id,x.public_key).into_bytes();if !device_sig(&state,p.device_id.clone(),msg,sig.clone()).await?{return Err(ApiError::forbidden("signature_invalid"));}decoded.push((x.key_id,x.public_key,sig)); }
    let did=p.device_id;let user=p.username;let bv=req.bundle_version;let curve=req.curve25519_identity_key;let ed=req.ed25519_identity_key;let now=util::ts(util::now());let now2=now.clone();
    state.db.run(move|c|{let tx=c.transaction()?;tx.execute(r#"INSERT INTO ratchet_device_bundles(device_id,username,bundle_version,curve25519_identity_key,ed25519_identity_key,signed_payload,signature,created_at,updated_at,revoked_at) VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?8,NULL) ON CONFLICT(device_id) DO UPDATE SET bundle_version=excluded.bundle_version,curve25519_identity_key=excluded.curve25519_identity_key,ed25519_identity_key=excluded.ed25519_identity_key,signed_payload=excluded.signed_payload,signature=excluded.signature,updated_at=excluded.updated_at,revoked_at=NULL"#,rusqlite::params![did,user,bv,curve,ed,payload,signature,now])?;for (kid,key,sig) in decoded{tx.execute("INSERT INTO ratchet_one_time_keys(device_id,key_id,public_key,signature,created_at) VALUES(?1,?2,?3,?4,?5) ON CONFLICT(device_id,key_id) DO NOTHING",rusqlite::params![did,kid,key,sig,now2])?;}tx.commit()?;Ok(())}).await.map_err(|e|if e.to_string().to_lowercase().contains("unique"){ApiError::conflict("ratchet_conflict")}else{ApiError::Internal(e)})?;
    state.events.bump();Ok(Json(json!({"version":VERSION,"status":"ok"})))
}

pub async fn claim(State(state):State<AppState>,headers:HeaderMap,Json(req):Json<Claim>)->ApiResult<Json<Value>> {
    let p=auth::authenticate(&state,&headers,true).await?;if req.version!=VERSION||req.target_device_id.is_empty()||req.target_device_id==p.device_id{return Err(ApiError::bad("invalid_request"));}
    let target=req.target_device_id;let me=p.username;let claimer=p.device_id;let now=util::ts(util::now());let now_out=now.clone();
    let row=state.db.run(move|c|{let tx=c.transaction()?;let r=tx.query_row(r#"SELECT b.device_id,b.username,b.bundle_version,b.curve25519_identity_key,b.ed25519_identity_key,b.signed_payload,b.signature,k.key_id,k.public_key,k.signature FROM ratchet_device_bundles b JOIN provisioning_devices d ON d.id=b.device_id JOIN ratchet_one_time_keys k ON k.device_id=b.device_id AND k.claimed_at IS NULL WHERE b.device_id=?1 AND b.revoked_at IS NULL AND d.revoked_at IS NULL AND d.security_state='READY' AND EXISTS(SELECT 1 FROM chat_members mine JOIN chat_members theirs ON theirs.chat_id=mine.chat_id WHERE mine.username=?2 AND theirs.username=b.username) ORDER BY k.created_at,k.key_id LIMIT 1"#,rusqlite::params![target,me],|r|Ok((r.get::<_,String>(0)?,r.get::<_,String>(1)?,r.get::<_,i64>(2)?,r.get::<_,String>(3)?,r.get::<_,String>(4)?,r.get::<_,Vec<u8>>(5)?,r.get::<_,Vec<u8>>(6)?,r.get::<_,String>(7)?,r.get::<_,String>(8)?,r.get::<_,Vec<u8>>(9)?))).optional()?.ok_or_else(||anyhow::anyhow!("no_key"))?;let n=tx.execute("UPDATE ratchet_one_time_keys SET claimed_at=?1,claimed_by_device_id=?2 WHERE device_id=?3 AND key_id=?4 AND claimed_at IS NULL",rusqlite::params![now,claimer,r.0,r.7])?;if n!=1{anyhow::bail!("conflict")};tx.commit()?;Ok(r)}).await.map_err(|e|match e.to_string().as_str(){"no_key"=>ApiError::not_found("one_time_key_unavailable"),"conflict"=>ApiError::conflict("ratchet_conflict"),_=>ApiError::Internal(e)})?;
    Ok(Json(json!({"version":VERSION,"device_id":row.0,"username":row.1,"bundle_version":row.2,"curve25519_identity_key":row.3,"ed25519_identity_key":row.4,"signed_payload":util::b64url(&row.5),"bundle_signature":util::b64url(&row.6),"one_time_key":{"key_id":row.7,"public_key":row.8,"signature":util::b64url(&row.9)},"claimed_at":now_out})))
}

pub async fn put_envelopes(State(state):State<AppState>,headers:HeaderMap,Json(req):Json<EnvelopeBatch>)->ApiResult<(StatusCode,Json<Value>)> {
    let p=auth::authenticate(&state,&headers,true).await?;if req.version!=VERSION||req.envelopes.is_empty()||req.envelopes.len()>64{return Err(ApiError::bad("invalid_request"));}
    let first=req.envelopes[0].message_id.clone();let mut seen=HashSet::new();let mut vals=Vec::new();
    for e in req.envelopes {if e.message_id!=first||e.recipient_device_id.is_empty()||!seen.insert(e.recipient_device_id.clone())||!valid_curve(&e.sender_curve25519_key)||e.session_id.len()<16||e.session_id.len()>256||!(0..=1).contains(&e.message_type){return Err(ApiError::bad("invalid_request"));}let ct=decode_url(&e.ciphertext,16,1<<20)?;let hash=hex::decode(&e.ciphertext_sha256).map_err(|_|ApiError::bad("invalid_request"))?;if hash.len()!=32||util::sha256(&ct).as_slice()!=hash.as_slice(){return Err(ApiError::bad("invalid_request"));}vals.push((e,ct,hash));}
    let did=p.device_id;let mid=first;let now=util::ts(util::now());state.db.run(move|c|{let tx=c.transaction()?;let (chat,sender)=tx.query_row("SELECT chat_id,sender_device_id FROM messages WHERE id=?1 AND deleted_at IS NULL",[&mid],|r|Ok((r.get::<_,String>(0)?,r.get::<_,String>(1)?))).optional()?.ok_or_else(||anyhow::anyhow!("notfound"))?;if sender!=did{anyhow::bail!("forbidden")};for (e,ct,hash) in vals {let ok:i64=tx.query_row("SELECT COUNT(*) FROM provisioning_devices d JOIN chat_members m ON m.username=d.username JOIN ratchet_device_bundles b ON b.device_id=d.id AND b.revoked_at IS NULL WHERE d.id=?1 AND m.chat_id=?2 AND d.revoked_at IS NULL AND d.security_state='READY'",rusqlite::params![e.recipient_device_id,chat],|r|r.get(0))?;if ok!=1{anyhow::bail!("forbidden")};tx.execute("INSERT INTO ratchet_message_envelopes(message_id,recipient_device_id,sender_curve25519_key,session_id,message_type,ciphertext,ciphertext_sha256,created_at) VALUES(?1,?2,?3,?4,?5,?6,?7,?8) ON CONFLICT(message_id,recipient_device_id) DO NOTHING",rusqlite::params![e.message_id,e.recipient_device_id,e.sender_curve25519_key,e.session_id,e.message_type,ct,hash,now])?;}tx.commit()?;Ok(())}).await.map_err(|e|match e.to_string().as_str(){"notfound"=>ApiError::not_found("message_not_found"),"forbidden"=>ApiError::forbidden("forbidden"),_=>ApiError::Internal(e)})?;state.events.bump();Ok((StatusCode::CREATED,Json(json!({"version":VERSION,"status":"ok"}))))
}

pub async fn list_envelopes(State(state):State<AppState>,headers:HeaderMap,Query(q):Query<EnvelopeQuery>)->ApiResult<Json<Value>> {
    let p=auth::authenticate(&state,&headers,true).await?;let after=q.after_sequence.unwrap_or(0);let limit=q.limit.unwrap_or(100);if after<0||!(1..=200).contains(&limit){return Err(ApiError::bad("invalid_request"));}let did=p.device_id;
    let out=state.db.run(move|c|{let mut s=c.prepare("SELECT e.message_id,e.recipient_device_id,e.sender_curve25519_key,e.session_id,e.message_type,e.ciphertext,e.ciphertext_sha256,m.chat_id,m.sender_device_id,e.created_at FROM ratchet_message_envelopes e JOIN messages m ON m.id=e.message_id WHERE e.recipient_device_id=?1 AND m.sequence>?2 AND m.deleted_at IS NULL ORDER BY m.sequence LIMIT ?3")?;let rows=s.query_map(rusqlite::params![did,after,limit],|r|{let ct:Vec<u8>=r.get(5)?;let h:Vec<u8>=r.get(6)?;Ok(json!({"message_id":r.get::<_,String>(0)?,"recipient_device_id":r.get::<_,String>(1)?,"sender_curve25519_key":r.get::<_,String>(2)?,"session_id":r.get::<_,String>(3)?,"message_type":r.get::<_,i64>(4)?,"ciphertext":util::b64url(&ct),"ciphertext_sha256":hex::encode(h),"chat_id":r.get::<_,String>(7)?,"sender_device_id":r.get::<_,String>(8)?,"created_at":r.get::<_,String>(9)?}))})?.collect::<Result<Vec<_>,_>>()?;Ok(rows)}).await.map_err(ApiError::Internal)?;Ok(Json(json!({"version":VERSION,"envelopes":out})))
}

pub async fn reserve_group(State(state):State<AppState>,headers:HeaderMap,Json(req):Json<Reserve>)->ApiResult<Json<Value>> {
    let p=auth::authenticate(&state,&headers,true).await?;if req.version!=VERSION||req.chat_id.is_empty()||req.rotation_id.len()<16||req.rotation_id.len()>128{return Err(ApiError::bad("invalid_request"));}member(&state,p.username.clone(),req.chat_id.clone()).await?;
    let chat=req.chat_id;let rot=req.rotation_id;let did=p.device_id;let now=util::now();let now_s=util::ts(now);let exp=util::ts(now+Duration::minutes(10));let rot_out=rot.clone();let chat_out=chat.clone();let exp_out=exp.clone();
    let (ver,replayed,expires_at)=state.db.run(move|c|{for _ in 0..8{let tx=c.transaction()?;if let Some((ch,d,v,expires,consumed))=tx.query_row("SELECT chat_id,sender_device_id,room_key_version,expires_at,consumed_at FROM megolm_rotation_reservations WHERE rotation_id=?1",[&rot],|r|Ok((r.get::<_,String>(0)?,r.get::<_,String>(1)?,r.get::<_,i64>(2)?,r.get::<_,String>(3)?,r.get::<_,Option<String>>(4)?))).optional()?{if ch!=chat||d!=did||consumed.is_some(){anyhow::bail!("conflict")};tx.commit()?;return Ok((v,true,expires));}let next:i64=tx.query_row("SELECT COALESCE(MAX(version),0)+1 FROM (SELECT room_key_version AS version FROM megolm_group_sessions WHERE chat_id=?1 UNION ALL SELECT room_key_version AS version FROM megolm_rotation_reservations WHERE chat_id=?1)",[&chat],|r|r.get(0))?;match tx.execute("INSERT INTO megolm_rotation_reservations(rotation_id,chat_id,sender_device_id,room_key_version,created_at,expires_at) VALUES(?1,?2,?3,?4,?5,?6)",rusqlite::params![rot,chat,did,next,now_s,exp]){Ok(_)=>{tx.commit()?;return Ok((next,false,exp.clone()));},Err(e) if e.to_string().to_lowercase().contains("constraint")=>continue,Err(e)=>return Err(e.into())}}anyhow::bail!("conflict")}).await.map_err(|e|if e.to_string()=="conflict"{ApiError::conflict("ratchet_conflict")}else{ApiError::Internal(e)})?;
    let _=exp_out;Ok(Json(json!({"version":VERSION,"chat_id":chat_out,"rotation_id":rot_out,"room_key_version":ver,"expires_at":expires_at,"replayed":replayed})))
}

pub async fn put_group(State(state):State<AppState>,headers:HeaderMap,Json(req):Json<GroupSession>)->ApiResult<(StatusCode,Json<Value>)> {
    let p=auth::authenticate(&state,&headers,true).await?;if req.version!=VERSION||req.chat_id.is_empty()||req.room_key_version<1||req.session_id.len()<16||req.session_id.len()>256||req.rotation_id.len()<16||req.rotation_id.len()>128||req.packages.is_empty()||req.packages.len()>64{return Err(ApiError::bad("invalid_request"));}member(&state,p.username.clone(),req.chat_id.clone()).await?;let mut pkgs=Vec::new();let mut seen=HashSet::new();for x in req.packages{if x.recipient_device_id.is_empty()||!seen.insert(x.recipient_device_id.clone())||x.olm_session_id.len()<16||x.olm_session_id.len()>256||!(0..=1).contains(&x.message_type){return Err(ApiError::bad("invalid_request"));}let enc=decode_url(&x.encrypted_session_key,16,65536)?;pkgs.push((x,enc));}
    let chat=req.chat_id;let ver=req.room_key_version;let sid=req.session_id;let rot=req.rotation_id;let did=p.device_id;let now=util::ts(util::now());
    state.db.run(move|c|{let tx=c.transaction()?;if let Some((ch,v,s,d))=tx.query_row("SELECT chat_id,room_key_version,session_id,sender_device_id FROM megolm_group_sessions WHERE rotation_id=?1",[&rot],|r|Ok((r.get::<_,String>(0)?,r.get::<_,i64>(1)?,r.get::<_,String>(2)?,r.get::<_,String>(3)?))).optional()?{if ch==chat&&v==ver&&s==sid&&d==did{return Ok(())}anyhow::bail!("conflict")};let reserved=tx.query_row("SELECT chat_id,sender_device_id,room_key_version,expires_at,consumed_at FROM megolm_rotation_reservations WHERE rotation_id=?1",[&rot],|r|Ok((r.get::<_,String>(0)?,r.get::<_,String>(1)?,r.get::<_,i64>(2)?,r.get::<_,String>(3)?,r.get::<_,Option<String>>(4)?))).optional()?.ok_or_else(||anyhow::anyhow!("conflict"))?;if reserved.0!=chat||reserved.1!=did||reserved.2!=ver||reserved.4.is_some()||util::parse_ts(&reserved.3)?<=util::now(){anyhow::bail!("conflict")};let expected:i64=tx.query_row("SELECT COUNT(*) FROM provisioning_devices d JOIN chat_members m ON m.username=d.username JOIN ratchet_device_bundles b ON b.device_id=d.id AND b.revoked_at IS NULL WHERE m.chat_id=?1 AND d.revoked_at IS NULL AND d.security_state='READY'",[&chat],|r|r.get(0))?;if seen.len() as i64!=expected{anyhow::bail!("conflict")};tx.execute("INSERT INTO megolm_group_sessions(chat_id,room_key_version,session_id,sender_device_id,rotation_id,created_at) VALUES(?1,?2,?3,?4,?5,?6)",rusqlite::params![chat,ver,sid,did,rot,now])?;for (x,enc) in pkgs{let ok:i64=tx.query_row("SELECT COUNT(*) FROM provisioning_devices d JOIN chat_members m ON m.username=d.username JOIN ratchet_device_bundles b ON b.device_id=d.id AND b.revoked_at IS NULL WHERE d.id=?1 AND m.chat_id=?2 AND d.revoked_at IS NULL AND d.security_state='READY'",rusqlite::params![x.recipient_device_id,chat],|r|r.get(0))?;if ok!=1{anyhow::bail!("forbidden")};tx.execute("INSERT INTO megolm_key_packages(chat_id,room_key_version,recipient_device_id,olm_session_id,message_type,encrypted_session_key,created_at) VALUES(?1,?2,?3,?4,?5,?6,?7)",rusqlite::params![chat,ver,x.recipient_device_id,x.olm_session_id,x.message_type,enc,now])?;}let n=tx.execute("UPDATE megolm_rotation_reservations SET consumed_at=?1 WHERE rotation_id=?2 AND consumed_at IS NULL",rusqlite::params![now,rot])?;if n!=1{anyhow::bail!("conflict")};tx.execute("UPDATE room_rotation_events SET completed_at=?1 WHERE chat_id=?2 AND new_key_version=?3 AND completed_at IS NULL",rusqlite::params![now,chat,ver])?;tx.commit()?;Ok(())}).await.map_err(|e|match e.to_string().as_str(){"conflict"=>ApiError::conflict("ratchet_conflict"),"forbidden"=>ApiError::forbidden("forbidden"),_=>ApiError::Internal(e)})?;state.events.bump();Ok((StatusCode::CREATED,Json(json!({"version":VERSION,"status":"ok"}))))
}

pub async fn list_packages(State(state):State<AppState>,headers:HeaderMap,Query(q):Query<PackageQuery>)->ApiResult<Json<Value>> {let p=auth::authenticate(&state,&headers,true).await?;let limit=q.limit.unwrap_or(100);if !(1..=200).contains(&limit){return Err(ApiError::bad("invalid_request"));}let did=p.device_id;let list=state.db.run(move|c|{let mut s=c.prepare("SELECT p.chat_id,p.room_key_version,g.session_id,g.sender_device_id,b.curve25519_identity_key,g.rotation_id,p.olm_session_id,p.message_type,p.encrypted_session_key,p.created_at FROM megolm_key_packages p JOIN megolm_group_sessions g ON g.chat_id=p.chat_id AND g.room_key_version=p.room_key_version JOIN ratchet_device_bundles b ON b.device_id=g.sender_device_id AND b.revoked_at IS NULL WHERE p.recipient_device_id=?1 AND p.consumed_at IS NULL ORDER BY p.created_at LIMIT ?2")?;let rows=s.query_map(rusqlite::params![did,limit],|r|{let e:Vec<u8>=r.get(8)?;Ok(json!({"chat_id":r.get::<_,String>(0)?,"room_key_version":r.get::<_,i64>(1)?,"session_id":r.get::<_,String>(2)?,"sender_device_id":r.get::<_,String>(3)?,"sender_curve25519_key":r.get::<_,String>(4)?,"rotation_id":r.get::<_,String>(5)?,"olm_session_id":r.get::<_,String>(6)?,"message_type":r.get::<_,i64>(7)?,"encrypted_session_key":util::b64url(&e),"created_at":r.get::<_,String>(9)?}))})?.collect::<Result<Vec<_>,_>>()?;Ok(rows)}).await.map_err(ApiError::Internal)?;Ok(Json(json!({"version":VERSION,"packages":list}))) }

pub async fn consume_package(State(state):State<AppState>,headers:HeaderMap,Json(req):Json<Consume>)->ApiResult<Json<Value>> {let p=auth::authenticate(&state,&headers,true).await?;if req.version!=VERSION||req.chat_id.is_empty()||req.room_key_version<1{return Err(ApiError::bad("invalid_request"));}let did=p.device_id;let chat=req.chat_id;let ver=req.room_key_version;let now=util::ts(util::now());let n=state.db.run(move|c|Ok(c.execute("UPDATE megolm_key_packages SET consumed_at=?1 WHERE chat_id=?2 AND room_key_version=?3 AND recipient_device_id=?4 AND consumed_at IS NULL",rusqlite::params![now,chat,ver,did])?)).await.map_err(ApiError::Internal)?;if n!=1{return Err(ApiError::not_found("group_key_not_found"));}Ok(Json(json!({"version":VERSION,"status":"ok"}))) }
