# Keep only metadata required by Kotlin, Compose, and future serialized models.
-keepattributes Signature,InnerClasses,EnclosingMethod
-keepattributes RuntimeVisibleAnnotations,RuntimeInvisibleAnnotations

# Do not suppress warnings or keep entire dependency namespaces. Add narrow rules only
# when a release build demonstrates a reflection boundary that R8 cannot infer.

# FedMes 1.0.4 hardening. This raises reverse-engineering cost; it cannot make APK decompilation impossible.
-repackageclasses f
-renamesourcefileattribute SourceFile
-adaptclassstrings

-assumenosideeffects class android.util.Log {
    public static *** v(...);
    public static *** d(...);
    public static *** i(...);
}

# FedMes shared Go crypto core generated by gomobile.
-keep class com.fedmes.crypto.mobile.** { *; }
-keep class go.** { *; }
-dontwarn go.**
